"""Adding pre_registration table

Revision ID: 3bfb2b7ed7bb
Revises: 9de69149f899
Create Date: 2026-09-14 05:47:23.778196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3bfb2b7ed7bb'
down_revision: Union[str, Sequence[str], None] = '9de69149f899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_notes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('transcript',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('duration_sec',
               existing_type=sa.FLOAT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('beta_signups', schema=None) as batch_op:
        batch_op.alter_column('interested',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'not_interested'"))
        batch_op.alter_column('signed_up_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=160),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('cover_image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('published_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('collection_files', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=160),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('attached_logs',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('original_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'GIF', name='mediatype'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'GIF', name='notemediatype'),
               existing_nullable=False)
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('duration_sec',
               existing_type=sa.FLOAT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('note_comments', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('note_media', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'GIF', name='notemediatype'),
               existing_nullable=False)
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('plain_text',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('pinned',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('SYSTEM_ALERT', 'INVITE', 'PRODUCT_UPDATE', 'INFO', 'SUCCESS', 'WARNING', 'ERROR', 'MENTION', 'NEW_MESSAGE', 'COMMENT', 'SHARE_INVITE', name='notificationtype'),
               existing_nullable=False)
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('used',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('revoked',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NOTE', 'FILE', 'FOLDER', 'COLLECTION', name='shareresourcetype'),
               existing_nullable=False)
        batch_op.alter_column('permission',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('VIEW', 'EDIT', name='sharepermission'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='sharestatus'),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('INFO', 'WARNING', 'ERROR', 'DEBUG', name='loglevel'),
               existing_nullable=False)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('user_onboarding', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('skipped',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('current_step',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'welcome'"))
        batch_op.alter_column('completed_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('reset_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=6),
               existing_nullable=True)
        batch_op.alter_column('reset_code_expires_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('is_developer',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('workspace_states', schema=None) as batch_op:
        batch_op.alter_column('state_data',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_states', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('state_data',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_developer',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reset_code_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('reset_code',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user_onboarding', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('current_step',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'welcome'"))
        batch_op.alter_column('skipped',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('completed',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('version',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('label',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.Enum('INFO', 'WARNING', 'ERROR', 'DEBUG', name='loglevel'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='sharestatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('permission',
               existing_type=sa.Enum('VIEW', 'EDIT', name='sharepermission'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
        batch_op.alter_column('resource_type',
               existing_type=sa.Enum('NOTE', 'FILE', 'FOLDER', 'COLLECTION', name='shareresourcetype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('revoked',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('used',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('archived',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('read',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('SYSTEM_ALERT', 'INVITE', 'PRODUCT_UPDATE', 'INFO', 'SUCCESS', 'WARNING', 'ERROR', 'MENTION', 'NEW_MESSAGE', 'COMMENT', 'SHARE_INVITE', name='notificationtype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('pinned',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('plain_text',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('note_media', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('caption',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'GIF', name='notemediatype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('note_comments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('duration_sec',
               existing_type=sa.Float(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'GIF', name='notemediatype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'GIF', name='mediatype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.alter_column('size_bytes',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('original_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('attached_logs',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('doc_pages', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('collection_files', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('cover_image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)

    with op.batch_alter_table('beta_signups', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('signed_up_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'not_interested'"))
        batch_op.alter_column('interested',
               existing_type=sa.Boolean(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('audio_notes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('size_bytes',
               existing_type=sa.Integer(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('duration_sec',
               existing_type=sa.Float(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('transcript',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
