"""ensuring onboarding tables exist

Revision ID: e1ed6b1f6e12
Revises: 8d9824ae545e
Create Date: 2026-09-08 02:08:02.043919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ed6b1f6e12'
down_revision: Union[str, Sequence[str], None] = '8d9824ae545e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
