"""add password reset code fields to users table

Revision ID: 81d6444cc9c8
Revises: 40b851d869d6
Create Date: 2026-08-26 19:16:25.579246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d6444cc9c8'
down_revision: Union[str, Sequence[str], None] = '40b851d869d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_code'), 'users', ['reset_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_code'), table_name='users')
    op.drop_column('users', 'reset_code_expires_at')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
