"""add archived to notifications

Revision ID: fdf2a45e8250
Revises: 9ac9d0a88b4f
Create Date: 2026-07-16 02:08:15.403219

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdf2a45e8250'
down_revision: str | Sequence[str] | None = '9ac9d0a88b4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade.
    
    Returns:
        None: None result.
    """
    op.add_column(
        "notifications",
        sa.Column("archived", sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )

def downgrade() -> None:
    """Downgrade.
    
    Returns:
        None: None result.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'archived')
    # ### end Alembic commands ###
