"""add attached_logs to feedback

Revision ID: 6142d82b09d6
Revises: cda6a49d0ae6
Create Date: 2026-08-18 18:17:23.931336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6142d82b09d6'
down_revision: Union[str, Sequence[str], None] = 'cda6a49d0ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('attached_logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'attached_logs')
    # ### end Alembic commands ###
