"""creation of tables

Revision ID: 7f1a6f6e5b41
Revises: 193d2f5ccab2
Create Date: 2026-07-26 19:15:39.686378

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '7f1a6f6e5b41'
down_revision: str | Sequence[str] | None = '193d2f5ccab2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade.
    
    Returns:
        None: None result.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade.
    
    Returns:
        None: None result.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
