"""added user auth tables

Revision ID: bd3d21e44edf
Revises: 2fbd45f40986
Create Date: 2026-07-30 01:18:55.364835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3d21e44edf'
down_revision: Union[str, Sequence[str], None] = '2fbd45f40986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('resource_type', sa.Enum('NOTE', 'FILE', 'FOLDER', 'COLLECTION', name='shareresourcetype'), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=True),
    sa.Column('permission', sa.Enum('VIEW', 'EDIT', name='sharepermission'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='sharestatus'), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_token'), 'shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_token'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
