"""Add is_developer flag to users

Revision ID: 4eb4bdf4683e
Revises: 10f0c0a65075
Create Date: 2026-07-27 18:29:38.220717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb4bdf4683e'
down_revision: Union[str, Sequence[str], None] = '10f0c0a65075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'is_developer',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_developer')
    # ### end Alembic commands ###
