"""expand_notification_types

Revision ID: 9ac9d0a88b4f
Revises: 6fcfec8263f6
Create Date: 2026-07-15 19:06:55.605257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac9d0a88b4f'
down_revision: Union[str, Sequence[str], None] = '6fcfec8263f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
