"""add archived to notifications

Revision ID: fdf2a45e8250
Revises: 9ac9d0a88b4f
Create Date: 2026-07-16 02:08:15.403219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf2a45e8250'
down_revision: Union[str, Sequence[str], None] = '9ac9d0a88b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "notifications",
        sa.Column("archived", sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'archived')
    # ### end Alembic commands ###
