"""Alembic environment configuration script."""

# pylint: disable=no-member, wrong-import-position, protected-access, unused-import
# isort: off

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path
from typing import Any, Union

from alembic import context
from alembic.runtime.migration import MigrationContext
from sqlalchemy import CHAR, Column, String, engine_from_config, pool
from sqlalchemy.types import TypeEngine

# ── 1. ADD PROJECT ROOT BEFORE ANY APP IMPORTS ────────────────────────
#
# This file is located at:
#
# app/database/migrations/env.py
#
# parents[0] = app/database/migrations
# parents[1] = app/database
# parents[2] = app
# parents[3] = project root
#
PROJECT_ROOT = Path(__file__).resolve().parents[3]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ── 2. APPLICATION IMPORTS ────────────────────────────────────────────

from app.core.config import settings
from app.database.base import Base
from app.database.types import GUID

# Models must be imported so that Base.metadata is fully populated.
import app.models  # noqa: F401  # type: ignore[unused-import]

# isort: on

# ── 3. ALEMBIC CONFIGURATION ──────────────────────────────────────────

config = context.config

# ── 4. DATABASE URL ───────────────────────────────────────────────────

config.set_main_option(
    "sqlalchemy.url",
    settings.DATABASE_URL,
)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ── 5. TARGET METADATA ────────────────────────────────────────────────

target_metadata = Base.metadata

# ── 6. TYPE COMPARISON ────────────────────────────────────────────────


def compare_type(
    migration_context: MigrationContext,
    inspected_column: Column[Any],
    metadata_column: Column[Any],
    inspected_type: TypeEngine[Any],
    metadata_type: TypeEngine[Any],
) -> bool:
    """Compare reflected database types with SQLAlchemy metadata.

    SQLite stores GUID values as character strings while PostgreSQL
    uses native UUID values.

    Existing SQLite CHAR/VARCHAR UUID columns should therefore be
    considered equivalent to the application's GUID type.

    Returns:
        True:
            Alembic should generate a type migration.

        False:
            Alembic should consider the types equivalent.
    """
    del inspected_column
    del metadata_column

    dialect = migration_context.dialect

    if (
        dialect.name == "sqlite"
        and isinstance(metadata_type, GUID)
        and isinstance(inspected_type, (String, CHAR))
    ):
        return False

    # Alembic itself uses this method for type affinity comparison.
    # type: ignore[protected-access]
    return inspected_type._compare_type_affinity(metadata_type)


# ── 7. AUTOGENERATE RENDERING ─────────────────────────────────────────


def render_item(type_: str, obj: Any, autogen_context: Any) -> Union[str, bool]:
    """Render custom types in autogenerated migrations.

    Ensures GUID columns are rendered with a short, readable call and
    that the corresponding import is automatically added to any
    migration file Alembic generates, rather than silently emitting an
    unimported ``app.database.types.GUID(...)`` reference.
    """
    if type_ == "type" and isinstance(obj, GUID):
        autogen_context.imports.add("from app.database.types import GUID")
        return "GUID(length=%r)" % obj.length
    return False


# ── 8. OFFLINE MIGRATIONS ─────────────────────────────────────────────

def run_migrations_offline() -> None:
    """Run migrations in offline mode."""
    url = config.get_main_option("sqlalchemy.url")

    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=compare_type,
        render_item=render_item,
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


# ── 9. ONLINE MIGRATIONS ──────────────────────────────────────────────

def run_migrations_online() -> None:
    """Run migrations in online mode."""
    connectable = engine_from_config(
        config.get_section(
            config.config_ini_section,
            {},
        ),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=compare_type,
            render_item=render_item,
            render_as_batch=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# ── 10. RUN ────────────────────────────────────────────────────────────

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
